// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/teamlumos/terraform-provider-lumos/internal/sdk/internal/utils"
)

type RequestApprovalConfigOutput struct {
	// Indicates if approval flow is overridden.
	RequestApprovalConfigOverride *bool `json:"request_approval_config_override,omitempty"`
	// Manager approval can be configured as necessary to continue
	ManagerApproval *ManagerApprovalOption `json:"manager_approval,omitempty"`
	// Only turn on when working with sensitive permissions to ensure a smooth employee experience.
	RequireAdditionalApproval *bool `json:"require_additional_approval,omitempty"`
	// After the approval step, send a custom message to requesters. Note that the permission level approval message will override the App level approval message if custom_approval_message_override is set. Markdown for links and text formatting is supported.
	CustomApprovalMessage *string `json:"custom_approval_message,omitempty"`
	// Indicates if custom_approval_message is overridden.
	CustomApprovalMessageOverride *bool `json:"custom_approval_message_override,omitempty"`
	// AppStore App approvers assigned.
	Approvers *AppApproversOutput `json:"approvers,omitempty"`
	// AppStore App stage 2 approvers assigned.
	ApproversStage2 *AppApproversOutput `json:"approvers_stage_2,omitempty"`
	// The stages of this request approval.
	RequestApprovalStages []RequestApprovalStageOutput `json:"request_approval_stages"`
}

func (r RequestApprovalConfigOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RequestApprovalConfigOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *RequestApprovalConfigOutput) GetRequestApprovalConfigOverride() *bool {
	if o == nil {
		return nil
	}
	return o.RequestApprovalConfigOverride
}

func (o *RequestApprovalConfigOutput) GetManagerApproval() *ManagerApprovalOption {
	if o == nil {
		return nil
	}
	return o.ManagerApproval
}

func (o *RequestApprovalConfigOutput) GetRequireAdditionalApproval() *bool {
	if o == nil {
		return nil
	}
	return o.RequireAdditionalApproval
}

func (o *RequestApprovalConfigOutput) GetCustomApprovalMessage() *string {
	if o == nil {
		return nil
	}
	return o.CustomApprovalMessage
}

func (o *RequestApprovalConfigOutput) GetCustomApprovalMessageOverride() *bool {
	if o == nil {
		return nil
	}
	return o.CustomApprovalMessageOverride
}

func (o *RequestApprovalConfigOutput) GetApprovers() *AppApproversOutput {
	if o == nil {
		return nil
	}
	return o.Approvers
}

func (o *RequestApprovalConfigOutput) GetApproversStage2() *AppApproversOutput {
	if o == nil {
		return nil
	}
	return o.ApproversStage2
}

func (o *RequestApprovalConfigOutput) GetRequestApprovalStages() []RequestApprovalStageOutput {
	if o == nil {
		return nil
	}
	return o.RequestApprovalStages
}
